### ISSUE TITLE
Mobile app takes long to launch 

### ISSUE THREAD

**Issue by Empressjanine** [h-unterp/fiduc-bugs#33] opened 2023-02-06 18:14 UTC
**Describe the bug**
The mobile app takes long to initialize 

**To Reproduce**
1. Be connected to a Wi-Fi network 
2. Launch the mobile app 

**Expected behavior**
The app should open fast especially when connected to a wireless network.
**Screen Recordings **
https://user-images.githubusercontent.com/93427231/217050083-92854a56-be7d-4b84-9fb4-ea4358c35374.MOV

**Smartphone (please complete the following information):**
 - Device: [Iphone 14]
 - OS: [IOS 16.0.3]
 - IMazing 2.16.9
 - Fiducia Version (0.3.8)
App console log file**
[FIDSOCIAL.TXT](https://github.com/h-unterp/fiduc-bugs/files/10667847/FIDSOCIAL.TXT)

**Comment by h-unterp** [comment] 2023-02-06 19:02
I can't see the video, can you trim to < 1 minute which should get you under the 50mb limit? Thank you

**Comment by Empressjanine** [comment] 2023-02-06 19:14
Find attached the recording to the issue, let me know if you are able to view it. Thanks 
https://user-images.githubusercontent.com/93427231/217063511-d0405831-033e-42f6-9974-1446bdaf3006.MOV

**Comment by h-unterp** [comment] 2023-02-06 19:42
![IMG_1851](https://user-images.githubusercontent.com/772917/217069133-6958ba7a-af16-4b39-b631-44b0903606db.PNG)
Still cannot see. This image (click info "I" button) is how to see video file size in gallery: is yours under 50mb?

**Comment by Empressjanine** [comment] 2023-02-06 19:49
Yes , mine is under 1mb . Don’t know why it’s not viewable.

https://user-images.githubusercontent.com/93427231/217070319-32a6b27f-04e2-4a12-8926-f3d768ae8e2e.MOV

Uploading IMG_1321.MOV…

**Comment by h-unterp** [comment] 2023-02-06 19:50
who knows. can you send via email please and reference bug in link? Thank you

**Comment by h-unterp** [comment] 2023-02-06 19:51
now I see it!

**Comment by Empressjanine** [comment] 2023-02-06 19:53
Great.

**Comment by h-unterp** [comment] 2023-02-06 20:02
Thank you for the console logs, however in production builds there is very little information that comes through. No need to do that again, but very cool thank you!

**Comment by Empressjanine** [comment] 2023-02-06 20:07
Thanks for the advice, highly appreciated and will note it down.

**Comment by h-unterp** [comment] 2023-02-06 21:46
I am unable to reproduce. Closing. Please reopen if you see it again

**Closed as completed by h-unterp** 2023-02-06 21:46 UTC
Labels: bug

**Comment by Empressjanine** [comment] 2023-02-07 00:29
Fixed , thanks.
