### ISSUE TITLE
0.0.16 GIF motion problem

### ISSUE THREAD

**Issue by bcrace18** [h-unterp/fiduc-bugs#14] opened 2022-11-18 04:36 UTC
**Describe the bug**
I uploaded a GIF but it had no motion. 

**To Reproduce**
1. Go to the upload
2. Click on gif
3. post gif
4. gif is static

**Expected behavior**
the gif should move like a film

**Screen Recordings and Screenshots**
![IMG_9038](https://user-images.githubusercontent.com/118379182/202617727-d6adba36-1f63-40ef-aab9-54c5123d605f.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 15.4.1
 - Fiducia Version 0.0.16

**Comment by h-unterp** [comment] 2022-11-18 12:54
Noted. Thank you

**Comment by h-unterp** [comment] 2022-11-19 12:13
Duplicate of https://github.com/h-unterp/fiduc-bugs/issues/14

**Closed as completed by h-unterp** 2022-11-19 12:13 UTC
Labels: bug

**Comment by h-unterp** [comment] 2022-11-19 12:15
duplicate of https://github.com/h-unterp/fiduc-bugs/issues/13
